const store={get:k=>JSON.parse(localStorage.getItem(k)||'[]'),set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
let customers=store.get('customers'),staff=store.get('staff'),contracts=store.get('contracts'),accruals=store.get('accruals');
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const fmt=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:2}).format(Number(n||0));
const monthKey=()=>new Date().toISOString().slice(0,7);
$('#monthName').textContent=new Intl.DateTimeFormat('tr-TR',{month:'long',year:'numeric'}).format(new Date());
function openView(id){$$('.view').forEach(v=>v.classList.remove('active-view'));$('#'+id).classList.add('active-view');$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===id));closeMenu();renderAll()}
function openMenu(){$('#sidebar').classList.add('open');$('#overlay').classList.add('show')}
function closeMenu(){$('#sidebar').classList.remove('open');$('#overlay').classList.remove('show')}
$('#menuBtn').onclick=openMenu;$('#closeMenuBtn').onclick=closeMenu;$('#overlay').onclick=closeMenu;$$('[data-view]').forEach(b=>b.addEventListener('click',()=>openView(b.dataset.view)));
function todayStatus(c){const t=new Date().toISOString().slice(0,10);if(c.status==='draft')return'draft';if(c.status==='cancelled')return'cancelled';if(c.endDate<t)return'ended';return c.status}
function renderCustomers(){const el=$('#customerList');if(!customers.length){el.className='list-stack empty-state';el.textContent='Henüz müşteri eklenmedi.';return}el.className='list-stack';el.innerHTML=customers.map(c=>`<article class="list-item"><h4>${c.name}</h4><div class="list-meta"><span>${c.taxNo||'Vergi no yok'}</span><span>${c.phone||'Telefon yok'}</span><span class="badge ${c.status==='active'?'active':''}">${c.status==='active'?'Aktif':'Pasif'}</span></div></article>`).join('')}
function renderStaff(){const el=$('#staffList');if(!staff.length){el.className='list-stack empty-state';el.textContent='Henüz personel eklenmedi.';return}el.className='list-stack';el.innerHTML=staff.map(s=>`<article class="list-item"><h4>${s.name}</h4><div class="list-meta"><span>${s.role||'Satış personeli'}</span><span class="badge ${s.status==='active'?'active':''}">${s.status==='active'?'Aktif':'Pasif'}</span></div></article>`).join('')}
function periodText(c){const map={daily:'Günlük',specificDays:'Belirli günler',daysPerWeek:'Haftada belirli gün',weekly:'Haftalık',monthly:'Aylık',oneTime:'Tek seferlik'};let t=map[c.period]||c.period;if(c.weekDays?.length)t+=' · '+c.weekDays.join(', ');if(c.daysPerWeek)t+=` · ${c.daysPerWeek} gün`;return t}
function renderContracts(){const filter=$('#contractFilter').value;const list=contracts.filter(c=>filter==='all'||todayStatus(c)===filter);const el=$('#contractList');if(!list.length){el.className='list-stack empty-state';el.textContent='Bu filtrede sözleşme bulunmuyor.';return}el.className='list-stack';el.innerHTML=list.map(c=>{const customer=customers.find(x=>x.id===c.customerId);const seller=staff.find(x=>x.id===c.staffId);const st=todayStatus(c);return`<article class="list-item"><div class="section-title-row"><div><h4>${customer?.name||'Müşteri silinmiş'}</h4><div class="muted">${c.name}</div></div><span class="badge ${st==='active'?'active':''}">${st==='active'?'Aktif':st==='ended'?'Sona erdi':st==='draft'?'Taslak':'İptal'}</span></div><div class="money">${fmt(c.amount)}</div><div class="list-meta"><span>${c.incomeCategory}</span><span>${periodText(c)}</span><span>${c.startDate} – ${c.endDate}</span><span>${seller?'Satış: '+seller.name:'Satış personeli yok'}</span><span class="badge ${c.paymentPattern==='irregular'?'irregular':''}">${c.paymentPattern==='irregular'?'Düzensiz ödeme':'Düzenli ödeme'}</span></div></article>`}).join('')}
function pendingAccruals(){const mk=monthKey();return contracts.filter(c=>todayStatus(c)==='active'&&c.accrualMethod==='fixed'&&!accruals.some(a=>a.contractId===c.id&&a.period===mk))}
function renderAccruals(){const list=pendingAccruals(),el=$('#accrualList');if(!list.length){el.className='list-stack empty-state';el.textContent='Bu ay için tahakkuk bekleyen kayıt yok.'}else{el.className='list-stack';el.innerHTML=list.map(c=>{const cu=customers.find(x=>x.id===c.customerId);return`<article class="list-item"><div class="section-title-row"><div><h4>${cu?.name||'Müşteri'}</h4><div class="muted">${c.incomeCategory} · ${c.name}</div></div><button class="primary-btn accrual-one" data-id="${c.id}">Tahakkuk Et</button></div><div class="money">${fmt(c.amount)}</div><div class="list-meta"><span>Tahakkuk günü: ${c.accrualDay}</span><span>${c.paymentPattern==='irregular'?'Düzensiz ödeme':'Düzenli ödeme'}</span></div></article>`}).join('');$$('.accrual-one').forEach(b=>b.onclick=()=>createAccrual(b.dataset.id))}const dash=$('#dashboardUpcoming');if(!list.length){dash.className='list-stack empty-state';dash.textContent='Henüz aktif sözleşme bulunmuyor.'}else{dash.className='list-stack';dash.innerHTML=list.slice(0,3).map(c=>{const cu=customers.find(x=>x.id===c.customerId);return`<article class="list-item"><div class="section-title-row"><div><h4>${cu?.name||'Müşteri'}</h4><div class="muted">${c.incomeCategory}</div></div><strong>${fmt(c.amount)}</strong></div></article>`}).join('')}}
function createAccrual(contractId){const c=contracts.find(x=>x.id===contractId);if(!c)return;accruals.push({id:crypto.randomUUID(),contractId,period:monthKey(),date:new Date().toISOString().slice(0,10),amount:Number(c.amount),status:'pending'});store.set('accruals',accruals);renderAll()}
$('#createAllAccruals').onclick=()=>pendingAccruals().forEach(c=>createAccrual(c.id));
function renderMetrics(){const active=contracts.filter(c=>todayStatus(c)==='active');$('#metricCustomers').textContent=customers.filter(c=>c.status==='active').length;$('#metricContracts').textContent=active.length;$('#metricMonthly').textContent=fmt(active.filter(c=>c.pricingType==='monthly'&&c.accrualMethod==='fixed').reduce((s,c)=>s+Number(c.amount),0));$('#metricUpcoming').textContent=pendingAccruals().length}
function fillSelects(){$('#contractCustomer').innerHTML='<option value="">Müşteri seçin</option>'+customers.filter(c=>c.status==='active').map(c=>`<option value="${c.id}">${c.name}</option>`).join('');$('#contractStaff').innerHTML='<option value="">Seçilmedi</option>'+staff.filter(s=>s.status==='active').map(s=>`<option value="${s.id}">${s.name}</option>`).join('')}
function renderAll(){renderCustomers();renderStaff();renderContracts();renderAccruals();renderMetrics();fillSelects()}
$('#newCustomerBtn').onclick=()=>$('#customerDialog').showModal();$('#newStaffBtn').onclick=()=>$('#staffDialog').showModal();$('#newContractBtn').onclick=()=>{fillSelects();if(!customers.length){alert('Önce bir müşteri eklemelisiniz.');openView('customers');return}$('#contractDialog').showModal()};
function formData(form){return Object.fromEntries(new FormData(form).entries())}
$('#customerForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const d=formData(e.target);customers.push({id:crypto.randomUUID(),...d});store.set('customers',customers);e.target.reset();$('#customerDialog').close();renderAll()});
$('#staffForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const d=formData(e.target);staff.push({id:crypto.randomUUID(),...d});store.set('staff',staff);e.target.reset();$('#staffDialog').close();renderAll()});
$('#contractForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const d=formData(e.target);d.weekDays=[...e.target.querySelectorAll('input[name="weekDays"]:checked')].map(x=>x.value);d.id=crypto.randomUUID();d.amount=Number(d.amount);contracts.push(d);store.set('contracts',contracts);e.target.reset();$('#specificDaysBox').classList.add('hidden');$('#daysPerWeekBox').classList.add('hidden');$('#contractDialog').close();renderAll()});
$('#periodSelect').onchange=e=>{$('#specificDaysBox').classList.toggle('hidden',e.target.value!=='specificDays');$('#daysPerWeekBox').classList.toggle('hidden',e.target.value!=='daysPerWeek')};$('#contractFilter').onchange=renderContracts;
renderAll();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
